# Requests persistent storage for the Monitoring Service's SQLite database and logs.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-pvc
spec:
  accessModes:
    - ReadWriteOnce # Allows read/write access from one node
  resources:
    requests:
      storage: 1Gi     # Requests 1 GiB of persistent storage
