# ============================================================
# POSTGRESQL DEPLOYMENT
# ============================================================

apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  replicas: 1 # run one postgresql pod

  selector:
    matchLabels:
      app: postgres # Deployment manages pods with this label

  template:
    metadata:
      labels:
        app: postgres   # Label assigned to the PostgreSQL pod

    spec:
      containers:

        - name: postgres  # Name of the PostgreSQL container

          image: postgres:16  # Uses PostgreSQL version 16 image

          ports:
            - containerPort: 5432 # PostgreSQL port

          env:

            - name: POSTGRES_DB # Database name used by PostgreSQL
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: postgres-db

            - name: POSTGRES_USER # PostgreSQL username
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: postgres-user # Reads username from ConfigMap

            - name: POSTGRES_PASSWORD # PostgreSQL password
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: postgres-password # Reads password securely from Secret

          volumeMounts:

            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              # Stores PostgreSQL database files in persistent storage

      volumes:

        - name: postgres-storage

          persistentVolumeClaim:
            claimName: postgres-pvc # Connects the pod to the PostgreSQL PersistentVolumeClaim


---

# ============================================================
# DATABASE API DEPLOYMENT
# ============================================================

apiVersion: apps/v1
kind: Deployment

metadata:
  name: database-service # Name of the Database Service deployment

spec:
  replicas: 2  # Runs Database API pod

  selector:
    matchLabels:
      app: database-service  # Selects pods belonging to this deployment

  template:
    metadata:
      labels:
        app: database-service  # Label assigned to the Database API pod

    spec:
      containers:

        - name: database-service  # Name of the Database API container

          image: sumyatmon17/database-api:v1  # Docker Hub image containing the FastAPI Database Service
          imagePullPolicy: Always
          # Pulls the latest published image from Docker Hub

          ports:
            - containerPort: 8000  # Port used by the FastAPI application

          env:

            - name: DATABASE_URL  # Database connection string used by the API
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: database-url # Retrieves the database URL securely from Kubernetes Secret
