# ============================================================
# POSTGRES SERVICE
# ============================================================

apiVersion: v1
kind: Service

metadata:
  name: postgres-service  # Name used to access PostgreSQL inside the cluster

spec:

  selector:
    app: postgres  # Routes traffic to pods labelled app: postgres

  ports:

    - port: 5432  # Port exposed by the Service
      targetPort: 5432 # Sends traffic to PostgreSQL container port 5432

  type: ClusterIP # Makes PostgreSQL accessible only within the cluster


---

# ============================================================
# DATABASE API SERVICE
# ============================================================

apiVersion: v1
kind: Service

metadata:
  name: database-service # Name used to access the Database API in the cluster

spec:

  selector:
    app: database-service  # Routes traffic to Database API pods

  ports:

    - port: 8000  # Port exposed by the Service
      targetPort: 8000 # Sends traffic to FastAPI container port 8000

  type: ClusterIP  # Makes the API accessible within the cluster